### PR TITLE
Update nvidia version

### PR DESCRIPTION
**Pull request by FML128**

### CODE REVIEW

**Comment by saltydk** [comment]
At least explain why you want to bump it. For individual needs you can just override the variable.

**Comment by FML128** [comment]
I had an issue installing it, this was fixed with the version bump. However, I am not sure if this was a one off or if this could affect other people.

**Comment by saltydk** [comment]
Provide any debugging done to narrow it to the version and I'll take a look and see if it is needed. We already run a newer driver than some would like.

**Comment by saltydk** [comment]
If nothing else would could just improve the docs on how to modify the version.

**Comment by FML128** [comment]
I was not aware, that some would like older drivers. I'll see if I can replicate it again.

This was what I did:
Upgraded hw. Same SSD.
Changed config to disable intel and activate nvidia.
sb install saltbox
-> Error could not install. Something with could not load nvidia_drm kernel module. (I tried this multiple times. Failed every time.)
changed version
sb install saltbox
works

**Comment by saltydk** [comment]
Yeah, we probably need a switch for the dkms to allow older drivers (for the GT users) or at least have an alternate driver path for them as the newer drivers don't work with such old hardware anymore. This probably belongs in an issue instead so the others can weigh in.

**Comment by FML128** [comment]
I cannot replicate it. No idea what happened. I'll close this.

**Comment by saltydk** [comment]
Thanks for trying though ;)

**Comment by saltydk** [comment]
https://discord.com/channels/853755447970758686/1136676425039085629 seems relevant now with the release of kernel 6.2 to Ubuntu HWE.

**Comment by saltydk** [comment]
Making another PR for traefik3 and I'll merge them both.

**Comment by owine** [comment]
> @FML128 I realize my auto correct effed up the previous reply, I meant to ask you to make the traefik3 PR, then you retain the credit for the edit. Apologies for only checking that now.

I will merge and cherry pick it over

**Comment by saltydk** [comment]
Thanks.

**Pull request merged**
