### PR TITLE
jaeger: map a volume for `/tmp`

### PR DESCRIPTION
**Pull request by powerdude**

### CODE REVIEW

**Comment by owine** [comment]
What's the purpose of adding this? I did not see any mentions in the project documentation.

**Comment by powerdude** [comment]
It may not be mentioned, but without it, portainer shows it as unmapped volume and they get left around after the container updates.

Thanks
________________________________

**Comment by owine** [comment]
```
[yaml[trailing-spaces]: roles/jaeger/defaults/main.yml#L94](https://github.com/saltyorg/Saltbox/pull/125/files#annotation_7222156260)
Trailing spaces
```

@saltydk would you prefer a tmpfs for this?

**Comment by owine** [comment]
```
[yaml[trailing-spaces]: roles/jaeger/defaults/main.yml#L94](https://github.com/saltyorg/Saltbox/pull/125/files#annotation_7222156260)
Trailing spaces
```

@saltydk would you prefer a tmpfs for this?

**Pull request merged**
