### PR TITLE
Add PowerDNS as DNS provider

### PR DESCRIPTION
**Pull request by patricksindelka**
Small change to add PowerDNS

### CODE REVIEW

**Comment by saltydk** [comment]
I've made a small edit to make the setting have a more descriptive name.

**Comment by saltydk** [comment]
I have already fixed the mistake with the variable, noticed it after committing.

**Comment by patricksindelka** [comment]
I agree that the name PowerDNS is better but pdns is the provider code in Traefik. If you change the name to PowerDNS, it also changes the value of the {{ traefik_challenge_provider }} field to that, which is used in the docker commands.

**Comment by saltydk** [comment]
I did not edit the ENV so I don't follow.

**Comment by saltydk** [comment]
I get your point now. I will try seeing if I can rename it under the hood
as pdns is not very descriptive.

**Comment by saltydk** [comment]
I have added a powerdns to pdns string replacement to the underlying variable so it should work fine now.

**Pull request merged**
