### PR TITLE
allow for custom log driver and log options on container creation

### PR DESCRIPTION
**Pull request by jolbol1**
This adds the ability for a user to customise the log driver and log options using `docker_log_driver` and `docker_log_options` in group vars all.yml, as well as allowing it per container `ROLE_docker_log_options` and `ROLE_docker_log_driver`. If none of these are present it will omit, thus using defaults.

This is useful for promtail and loki.

### CODE REVIEW

**Comment by saltydk** [comment]
localhost.yml is where users will edit anything. Not all.yml as that will get overwritten.

**Comment by jolbol1** [comment]
> localhost.yml is where users will edit anything. Not all.yml as that will get overwritten.

But you can still put docker_log_driver in localhost correct? 

Or is there another way to have a customisable global variable?

**Comment by saltydk** [comment]
Yes, that is how you do it. Was just letting you know since you seem to have misunderstood :)

**Comment by saltydk** [comment]
added something similar in https://github.com/saltyorg/Saltbox/commit/14001041558b8b891e3a324ca57c150ffd669f06

**Pull request closed without merging**
