### PR TITLE
Create box.j2

### PR DESCRIPTION
**Pull request by nachobel**
Template for a Box.com remote.

### CODE REVIEW

**Comment by owine** [comment]
Thanks for the PR. I know some use a chunker remote for Box. Is this for a standard Box remote, a chunker or both?

**Comment by nachobel** [comment]
This is for a box remote setup behind a clone chunked remote, mounting the chunker remote. It should work with a normal box remote as well though, but I haven’t tried it like that.

My first attempt at a PR!  I’m Alia over in the discord

**Comment by saltydk** [comment]
I suspect we'll setup a community repo for user submitted profiles. Just need to think on how to structure it. I will not be able to personally validate every submission so I kind of want to avoid having profiles in Saltbox itself if they haven't been tested by us. I will reply again on this PR when we've decided how to go about this as this will have a place somewhere either way it goes.

**Comment by owine** [comment]
Can you PR this to the new repo we have established for mount templates? https://github.com/saltyorg/mount-templates

I am closing this here but see no reason not to accept it on that templates repo

**Pull request closed without merging**
